### ISSUE TITLE
No usable version of libssl was found

### ISSUE THREAD

**Issue by mtjohnson47** [spikeydragoon/Cross-Ark-Chat#63] opened 2022-06-28 17:06 UTC
CrossArkChat does not work on Linux.  Apparently the issue is that .NET is using an outdated libssl, and you need to update .NET.
The program crashed when I ran the program.
Ubuntu 22.04 Server.
Log:

> CrossArkChat
> Version 6.2.1.0
> This program was created by Spikeydragoon all rights reserved.
> Thanks to Sowa for creating the application icon.
> Be sure to check out the bots official host ServerBlend.
> Use the command d!serverblend for more info.
> 
> No usable version of libssl was found
> Aborted

Config file
[_configuration.json.txt](https://github.com/spikeydragoon/Cross-Ark-Chat/files/9003284/_configuration.json.txt)
:

**Comment by spikeydragoon** [comment] 2022-06-29 22:02
> CrossArkChat does not work on Linux. Apparently the issue is that .NET is using an outdated libssl, and you need to update .NET. The program crashed when I ran the program. Ubuntu 22.04 Server. Log:
> 
> > CrossArkChat
> > Version 6.2.1.0
> > This program was created by Spikeydragoon all rights reserved.
> > Thanks to Sowa for creating the application icon.
> > Be sure to check out the bots official host ServerBlend.
> > Use the command d!serverblend for more info.
> > No usable version of libssl was found
> > Aborted
> 
> Config file [_configuration.json.txt](https://github.com/spikeydragoon/Cross-Ark-Chat/files/9003284/_configuration.json.txt) :

Yes if you run the latest ubuntu server I found out recently that happens. The one to report it said the one right before it still works with it.

**Comment by spikeydragoon** [comment] 2022-06-29 22:37
So looks like the issue is .net 3.1 and higher is wanting either openssl 1.1 and falls back to openssl 1.0 however ubuntu 22.04 is only coming with openssl 3 so to fix you can install libssl1.0 or 1.1 to get it working again.

**Comment by spikeydragoon** [comment] 2022-07-23 15:15
Closing due to no reply.

Feel free to open again if still having issues.

**Closed by spikeydragoon** 2022-07-23 15:15 UTC

**Comment by mtjohnson47** [comment] 2022-07-23 15:19
Oh, I didn't know I needed to reply.  I'm not going to downgrade libssl because I don't want to risk breaking ssh and getting locked out of the machine.  I've spent the last month trying to figure out how to create a custom pterodactyl (server manager) egg to use instead.
